name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
